---
title: "Getting up and running"
author: "Katherine von Duyke"
date: "8/27/2019"
output: html_document
---

## R Markdown
This is the website for R markdown how to: https://rmarkdown.rstudio.com/lesson-1.html

## statistical inference via datascience
This has a lot of beginner hints, and we'll come back to this for regression https://moderndive.com/index.html

## Github
Open a github account and add a lab.github.com repository to begin to learn how to use this important resource.

##efficient R programming
A source for optimizing your work: https://bookdown.org/csgillespie/efficientR/set-up.html#rstudio 

##A tutorial right in R study
install the package swirl - you can see what's available on github.
| To begin, you must install a course. I can install a course for you from the internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options and directions for installing courses
| yourself. 

Here is a quick list of courses

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
